---
  name: E2E Smoketests
  on:
    # For PRs, this workflow gets triggered from the Argo Events platform.
    # Check the following repo for details: https://github.com/mattermost/delivery-platform
    workflow_dispatch:
      inputs:
        commit_sha:
          type: string
          required: false

  jobs:
    e2e-smoketest:
      uses: ./.github/workflows/e2e-tests-ci-template.yml
      with:
        commit_sha: "${{ inputs.commit_sha || github.sha }}"
        status_check_context: "E2E Tests/smoketests"
      # TODO: remove, these will only be used in the full E2E test run
      secrets:
        MM_LICENSE: "${{ secrets.MM_E2E_LICENSE_ONPREM }}"
        AUTOMATION_DASHBOARD_URL: "${{ secrets.MM_E2E_AUTOMATION_DASHBOARD_URL }}"
        AUTOMATION_DASHBOARD_TOKEN: "${{ secrets.MM_E2E_AUTOMATION_DASHBOARD_TOKEN }}"
